apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: infra-tools
spec:
  project: default

  source:
    chart: postgresql
    repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: 18.6.10
    helm:
      releaseName: postgresql
      valuesObject:
        auth:
          username: mlflow
          password: mlflow-postgres-password
          database: mlflow

        primary:
          persistence:
            enabled: true
            storageClass: gp3
            size: 5Gi

          service:
            type: ClusterIP
            ports:
              postgresql: 5432

          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 300m
              memory: 512Mi

  destination:
    server: https://kubernetes.default.svc
    namespace: mlflow

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true